### ISSUE TITLE
Examples don't compile in XCode 7.2

### ISSUE THREAD

**Issue by ExoticObjects** [zmeyc/UITestUtils#1]
Lots of issues in swifter. I know that's not your code, but just letting you know. Also some issues in your XCTestCase extensions...

**Comment by zmeyc** [comment]
Thank you! I've updated Swifter to latest version and fixed the errors in extensions. UI tests in sample project now work in Xcode 7.2.

**Comment by ExoticObjects** [comment]
I don't think it's quite fixed. When I run Test (Command-U) on the Example App scheme in XCode 7.2 I get this error:

`No such module 'UITestUtils'` in `ExampleAppUITests.swift`

**Comment by zmeyc** [comment]
Please try switching to UITestUtils project in dropdown box and building it, then back to Example project. I guess Xcode didn't build it automatically.

**Comment by zmeyc** [comment]
I've added UITestUtils as a dependency of ExampleApp and pushed the changes, so this should be no longer neccesary.

**Comment by ExoticObjects** [comment]
It compiles now. But what happens for you when you test ExampleAppUITests? For me it crashes immediately - no info provided.

**Comment by zmeyc** [comment]
Does the app start successfully if runned (ALT-R)? Please make sure "ExampleApp" is selected on the top panel of Xcode. Also, I didn't test it with real devices, only on simulator.

**Comment by ExoticObjects** [comment]
Command-R (Run) form the Product Menu causes immediate crash. But wouldn't the point be to run Command-U to actually do the UI tests?

Are either of the GIT submodules meant to be set to a branch? Both of mine are - not sure if that's intended.

You should do a fresh checkout and try to run it.

**Comment by zmeyc** [comment]
Maybe the problem is with stuck simulator or something like that. The app should start without problems otherwise UI tests won't work.

No branches, just master + submodules:

git clone --recursive https://github.com/zmeyc/UITestUtils.git
open ExampleApp.xcodeproj
ALT-B
ALT-U

I've tried re-downloading from github, but it seems to work, I've recorded a step-by-step video:
https://youtu.be/6v7HXUjww4c

Xcode version: 7.2 (7C68)

**Comment by ExoticObjects** [comment]
- Verified setup. Project and submodules are on master branches.
- Cleaned project, cleared derived data.

Still crashes. The only thing that differs is that I'm using the beta for XCode 7.2 I guess that could be the issue, don't know.

Here's my video: http://exoticobjects.com/_projects/tmp/UITestUtilsDemo_odd.m4v

**Comment by zmeyc** [comment]
Is breakpoints pane empty? (it could be caused by "Stop on C++ exceptions" option being enabled)
Try pressing Ctrl-Cmd-Y when it triggers the breakpoint.

**Comment by zmeyc** [comment]
Pls post the stacktrace screenshot.

**Comment by ExoticObjects** [comment]
My bad. I forgot that XCode will apply 'User' breakpoints to whatever project I open. I assumed that any breakpoints in there would be yours, but my user breakpoints were there. Disabling them fixed the issue.

Sorry to put you through that!

**Comment by zmeyc** [comment]
No problem! :) I'm glad that it's solved.
