### ISSUE TITLE
is there any plan to support Swift 3/ Xcode 8?

### ISSUE THREAD

**Issue by chunfuchen** [zmeyc/UITestUtils#8]

**Comment by zmeyc** [comment]
I'm working on this in Swift3 branch.

**Comment by tinder-ayu** [comment]
@zmeyc Does this work on xcode 8 yet? I cloned swift3 branch and unable to get the example app to compile.

**Comment by zmeyc** [comment]
@tinder-ayu Not yet, the problem is with Swifter (HTTP server library). It used to be a tiny library, but it's now much more complex and can't be easily embedded. I'll probably just port the old version to Swift 3.

**Comment by zmeyc** [comment]
@tinder-ayu @chunfuchen Done. Everything should be working now on Swift 3 / Xcode 8 in master branch. Swifter & SimulatorStatusMagic submodules now point to my forks of these repositories, so please re-fetch them as well. Please reopen the issue if something doesn't work.
